services:
  - type: web
    name: odds-ai-v24-no-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MIN_START_MINUTES
        value: "10"
      - key: MAX_START_MINUTES
        value: "720"
      - key: ENABLE_BMBETS
        value: "1"
      - key: ALLOW_DEMO_FALLBACK
        value: "1"
